[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Root topic

## 登录流程
> leftSide=`true`


### LoginHelper\.Login

### Main2NetClient\_LoginHandler

#### main 纤程到NetClient纤程

#### Run

##### RouterAddressComponent

###### 负责根网关服务器通信，背后做了一些负载均衡的事情

##### NetComponent

##### FiberParentComponent set parent  fiberId as MainFiber

### 通信架构图
- FILE
<pre>Docs/DocImages/网络通信架构.png</pre>
