[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Root topic

## 协议日志过滤

### 修改LogMsg\.cs里面的过滤集，前后端都是

## 登录流程
> leftSide=`true`


### 客户端

#### LoginHelper\.Login

#### ProcessInnerSender 调用NetClient2Main\_Login

#### Main2NetClient\_LoginHandler

### 服务端
> leftSide=`true`


#### C2R\_LoginHandler

##### 处理完会关闭session

## Fiber的Init
> leftSide=`true`


### FiberInit\_XXX

## 数据库操作

### DBManagerComponent

### DBComponent

#### 通过DBManagerComonent 传入Zone信息拿到

#### 具体配置看 Config\\Excel\\StartConfig
